{{- if .Values.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    app: {{ template "kube-janitor.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kube-janitor.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
{{- if .Values.rbac.pspEnabled }}
  - apiGroups:
    - {{ template "rbac.pspApiGroup" . }}
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "kube-janitor.fullname" . }}
    verbs:
    - use
{{- end }}
{{- end -}}
