apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-janitor.fullname" . }}-config
  labels:
    app: {{ template "kube-janitor.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}