{{- $Name := include "kube-janitor.name" . -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "kube-janitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ $Name }}
    helm.sh/chart: {{ include "kube-janitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - mountPath: "/scan/reports"
                  name: kube-janitor-pvc
              env:
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kube-janitor
                      key: slack_token
                - name: CLUSTER_NAME
                  value: {{ .Values.cluster_name }}
              command: [ "python", "./main.py" ]
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
          volumeMounts:
            - name: config
              mountPath: /etc/kube-janitor/
        volumes:
          - name: config
            configMap:
              name: {{ template "kube-janitor.fullname" . }}-config