apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-janitor.serviceAccountName" . }}
  labels:
    app: {{ template "kube-janitor.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
