apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-janitor.serviceAccountName" . }}
  labels:
    {{- include "kube-janitor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
