# Default values for kube-janitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "0 7 * * MON"

image:
  repository: quay.io/verygoodsecurity/kube-janitor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: release-0.1.0

config:
  kube:
    kubectx: "kubectx"
    kubectl: "kubectl"
    context: ""

    slack:
      #token: "" # SLACK_TOKEN
      channel: ""

    resources:
      ns:
        whitelist:
          - kube-system
          - core
          - infra
        annotation_whitelist:
          - fluxcd.io

external_secrets:
  - key: /path/to/key
    name: slack_token

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
   cpu: 100m
   memory: 128Mi